CFLAG = -g -Wall -Wshadow

ball1: ball1.c
	gcc $(CFLAG) ball1.c -o $@

ball2: ball2.c
	gcc $(CFLAG) ball2.c -o $@

ball3: ball3.c
	gcc $(CFLAG) ball3.c -o $@

oneway: oneway.c
	gcc $(CFLAG) oneway.c -o $@

hanoi: hanoi.c
	gcc $(CFLAG) hanoi.c -o $@

partition: partition.c
	gcc $(CFLAG) partition.c -o $@

partition1: partition1.c
	gcc $(CFLAG) partition1.c -o $@
clean:
	rm ball1 ball2 ball3 oneway hanio partition

