CFLAG = -g -Wall -Wshadow

ball1: ball1.c
	gcc $(CFLAG) ball1.c -o $@

ball2: ball2.c
	gcc $(CFLAG) ball2.c -o $@

ball3: ball3.c
	gcc $(CFLAG) ball3.c -o $@

oneway: oneway.c
	gcc $(CFLAG) oneway.c -o $@

clean:
	rm ball1 ball2 ball3 oneway

